sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.2.3

before_install:
  - docker-compose build
env:
  - RAILS_ENV=test
script:
  - docker-compose up -d && docker ps
  - docker exec railsdockervagrantdevkit_web_1 bin/rake db:create db:migrate
  - docker exec railsdockervagrantdevkit_web_1 bin/bundle exec rspec
# - docker ps
# - sudo docker exec test_container bin/rspec spec
# - "export DISPLAY=:99.0"
# - "sh -e /etc/init.d/xvfb start"