sudo: required

services:
  - docker
  - postgresql
language: ruby

rvm:
  - 2.2.3

before_install:
  - docker-compose build
  - docker-compose up -d && docker ps
env:
  - RAILS_ENV=test
script:
  - docker exec railsdockervagrantdevkit_web_1 bin/rake db:create db:migrate
  - docker exec railsdockervagrantdevkit_web_1 bin/bundle exec rspec